CRITICAL 2022-04-25 16:18:40,874 - Our First Log Message
CRITICAL 2022-04-25 16:18:40,874 - error occurred
Traceback (most recent call last):
  File "D:\git\Tistory_blog\Python_basic\logger.py", line 22, in <module>
    print(1/0)
ZeroDivisionError: division by zero
